class CreateAuthentications < ActiveRecord::Migration
  def change
    create_table :authentications do |t|
      t.string :uid # string that uniquely identifies each user in providers db
      t.string :token # generated by the provider (facebook). Can be used if additional actions
                      # should be carried out on the users behalf (e.g get friends from facebook)
      t.string :provider
      t.references :user, index: true, foreign_key: true # user_id of the User in this apps database
        # 'references' has the same effect as adding belongs_to in the User Model
        # and creates the foreign_key in the db table
      t.timestamps null: false
    end
  end
end
